openapi: "3.0.0"
info:
  title: Trabook API
  description: REST API for Trabook, a travel booking platform
  version: 1.0.0
paths:
  /api/v1/:
    get:
      summary: Welcome Page
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to the Trabook API
  /api/v1/clients/:
    get:
      summary: List all Clients
      responses:
        '200':
          description: List of clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
    post:
      summary: Create Client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Client created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'

  /api/v1/clients/{id}/:
    get:
      summary: Retrieve Client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Client details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    put:
      summary: Update Client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Client updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    delete:
      summary: Delete Client
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Client deleted

  /api/v1/payment-methods/:
    get:
      summary: List all Payment Methods
      responses:
        '200':
          description: List of payment methods
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentMethod'
    post:
      summary: Create Payment Method
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentMethod'
      responses:
        '201':
          description: Payment Method created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethod'

  /api/v1/payment-methods/{id}/:
    get:
      summary: Retrieve Payment Method
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Payment Method details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethod'
    put:
      summary: Update Payment Method
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentMethod'
      responses:
        '200':
          description: Payment Method updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethod'
    delete:
      summary: Delete Payment Method
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Payment Method deleted

  /api/v1/continents/:
    get:
      summary: List all Continents
      responses:
        '200':
          description: List of continents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Continent'
    post:
      summary: Create Continent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Continent'
      responses:
        '201':
          description: Continent created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Continent'

    /api/v1/continents/{id}/:
      get:
        summary: Retrieve Continent
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Continent details
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Continent'
      put:
        summary: Update Continent
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Continent'
        responses:
          '200':
            description: Continent updated
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Continent'
      delete:
        summary: Delete Continent
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: Continent deleted

    /api/v1/countries/:
      get:
        summary: List all Countries
        responses:
          '200':
            description: List of countries
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Country'
      post:
        summary: Create Country
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        responses:
          '201':
            description: Country created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Country'

    /api/v1/countries/{id}/:
      get:
        summary: Retrieve Country
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Country details
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Country'
      put:
        summary: Update Country
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        responses:
          '200':
            description: Country updated
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Country'
      delete:
        summary: Delete Country
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: Country deleted

    /api/v1/destinations/:
      get:
        summary: List all Destinations
        responses:
          '200':
            description: List of destinations
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Destination'
      post:
        summary: Create Destination
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        responses:
          '201':
            description: Destination created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Destination'

    /api/v1/destinations/{id}/:
      get:
        summary: Retrieve Destination
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Destination details
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Destination'
      put:
        summary: Update Destination
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        responses:
          '200':
            description: Destination updated
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Destination'
      delete:
        summary: Delete Destination
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: Destination deleted

components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        middle_name:
          type: string
          required: false
        last_name:
          type: string

    PaymentMethod:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Continent:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Country:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        continent:
          type: integer
          description: existing continent id

    Destination:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        country:
          type: integer
          description: existing country id
